run:
  tests: false
  timeout: 10m
  concurrency: 4
  modules-download-mode: readonly

# https://golangci-lint.run/usage/linters/
linters:
  fast: false
  enable:
    # Enabled by default
    - deadcode
    - errcheck
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - structcheck
    - typecheck
    - unused
    - varcheck
    # Disabled by default, but desired for this project
    - bodyclose
    - exportloopref
    - godot
    - gofmt
    - goimports
    - makezero
    - misspell
    - revive
    - sqlclosecheck
    - unconvert
    - whitespace
