version: '3'

services:
  recon:
    image: vodeno:latest
    restart: unless-stopped
    build:
      context: ../..
      dockerfile: Dockerfile
    environment:
      DB_HOST: db
      PORT: 8080
      WATCHER_TICK_PERIOD: 5m
    ports:
      - "8080:8080"
    depends_on:
      - db

  db:
    image: postgres:14
    restart: unless-stopped
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
      - ./db/20211123163200_init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
    - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: vodeno
      POSTGRES_PASSWORD: postgres

volumes:
  postgres-data:
